apiVersion: v1
kind: Service
metadata:
  name: roundcube-db
  namespace: roundcube
  labels:
    app: roundcube-db
spec:
  ports:
  - port: 3306
    name: roundcube-db
  clusterIP: None
  selector:
    app: roundcube-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: roundcube-db
  namespace: roundcube
spec:
  selector:
    matchLabels:
      app: roundcube-db # has to match .spec.template.metadata.labels
  serviceName: "roundcube-db"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: roundcube-db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: roundcube-db
        image: mysql
        ports:
        - containerPort: 3306
          name: roundcube-db
        volumeMounts:
        - name: roundcube-hd
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: roundcube-hd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "azure-storage"
      resources:
        requests:
          storage: 1Gi