kind: Service
apiVersion: v1
metadata:
  name: roundcube
  namespace: roundcube
  labels:
    app: roundcube
spec:
  selector:
    app: roundcube
  ports:
    - name: http
      port: 80
      targetPort: http

---


---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: roundcube
  labels:
    app: roundcube
spec:
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
        version: 'fpm'
    spec:
      containers:
        - name: roundcube
          image: roundcube/roundcubemail
          env:
            - name: SHARE_APP
              value: '1'
          volumeMounts:
            - name: config
              subPath: roundcube.config.php
              mountPath: /app/config/config.inc.php
              readOnly: true
            - name: src
              mountPath: /shared
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: config
              subPath: nginx.vh.conf
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
            - name: src
              mountPath: /var/www
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: roundcube.config
        - name: src
          emptyDir: {}