kind: ConfigMap
apiVersion: v1
metadata:
  name: roundcube.config
  namespace: roundcube
  labels:
    app: roundcube
data:
  roundcube.config.php: |
    <?php
    $config = [];
    $config['db_dsnw'] = 'mysql:////var/lib/mysql/rouncube.db?mode=0640';

    $config['des_key'] = 'Change_me_I_am_example!!';
    $config['plugins'] = [
        'archive',
        'zipdownload',
    ];

  nginx.vh.conf:
    server {
        listen   80;
        root     /var/www/html;
        index    index.php;
        charset  utf-8;

        location = /favicon.ico {
            root /var/www/html/skins/larry/images;
            access_log     off;
            log_not_found  off;
            expires        max;
        }

        location = /robots.txt {
            allow          all;
            access_log     off;
            log_not_found  off;
        }

        location / {
            try_files $uri $uri/ index.php;
        }

        location ~ /\.ht {
            deny           all;
            access_log     off;
            log_not_found  off;
        }

        location ~* \.php$ {
            try_files      $uri =404;
            include        fastcgi_params;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass   localhost:9000;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            fastcgi_index  index.php;

        }
    }
