apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-storage
  namespace: roundcube
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: STORAGE_ACCOUNT